# Generated by Django 3.0.5 on 2020-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heimspiel_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, to="heimspiel_core.PlayerAttribute"
            ),
        ),
    ]
