# Generated by Django 3.0.5 on 2020-04-22 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("heimspiel_core", "0002_auto_20200422_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
